version: '3.8'

services:
  back:
    build: ./back
    container_name: back
    ports:
      - "5000:5000"
    networks:
      - app-network

  front:
    build: ./front
    container_name: front
    ports:
      - "5001:5001"
    depends_on:
      - back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
