name: Build, Test & Push to Docker Hub

on:
  push:
    branches:
      - main 
      - develop
  pull_request:
    branches:
      - main  

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings || exit 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-python-app .

      - name: Tag Docker image
        run: |
          docker tag my-python-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest
          docker images

      - name: Run Container
        run: docker run -d -p 5000:5000 --name my-python-app ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest

      - name: Test if Container is Running
        run: |
          sleep 5
          for i in {1..10}; do
            if curl --fail http://127.0.0.1:5000/; then
              echo "Server is up!"
              exit 0
            fi
            echo "Server not ready, retrying ($i/10)..."
            sleep 2
          done
          echo "Server did not start in time."
          exit 1

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest
