name: Build, Test & Push to Docker Hub

on:
  release:
    types:
      - created

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies for back-end
        run: |
          cd back
          pip install --no-cache-dir -r requirements.txt
          pip install pytest

      - name: Run tests for back-end
        run: |
          cd back
          pytest --maxfail=1 --disable-warnings || exit 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Docker image tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build back-end Docker image
        run: |
          docker build -f back/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/my-python-backend:latest ./back
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-python-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-python-backend:$IMAGE_TAG

      - name: Check back-end Docker image
        run: |
          docker images ${{ secrets.DOCKERHUB_USERNAME }}/my-python-backend

      - name: Build front-end Docker image
        run: |
          docker build -f front/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/my-python-frontend:latest ./front
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-python-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-python-frontend:$IMAGE_TAG

      - name: Check front-end Docker image
        run: |
          docker images ${{ secrets.DOCKERHUB_USERNAME }}/my-python-frontend

      - name: Run back-end Container
        run: |
          docker run -d -p 5000:5000 --name my-python-backend ${{ secrets.DOCKERHUB_USERNAME }}/my-python-backend:latest

      - name: Test if back-end Container is Running
        run: |
          sleep 5
          for i in {1..10}; do
            if curl --fail http://127.0.0.1:5000/; then
              echo "Back-end server is up!"
              exit 0
            fi
            echo "Back-end server not ready, retrying ($i/10)..."
            sleep 2
          done
          echo "Back-end server did not start in time."
          exit 1

      - name: Run front-end Container
        run: |
          docker run -d -p 5001:5001 --name my-python-frontend ${{ secrets.DOCKERHUB_USERNAME }}/my-python-frontend:latest

      - name: Test if front-end Container is Running
        run: |
          sleep 5
          for i in {1..10}; do
            if curl --fail http://127.0.0.1:5001/; then
              echo "Front-end server is up!"
              exit 0
            fi
            echo "Front-end server not ready, retrying ($i/10)..."
            sleep 2
          done
          echo "Front-end server did not start in time."
          exit 1

      - name: Push back-end Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-backend:$IMAGE_TAG

      - name: Push front-end Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-frontend:$IMAGE_TAG
